import Image from "next/image";
import Link from "next/link";
import {collections,products} from "@/data/catalog";
import {ProductCard} from "@/components/product/product-card";

export default function Home(){
return <main id="main-content">
<section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">NATURALLY YOURS</p><h1>Natural beauty,<br/>made to be <em>worn.</em></h1><p className="hero-description">Jewelry inspired by nature’s color and texture. Thoughtfully selected for your everyday moments.</p><div className="hero-buttons"><Link className="button" href="/shop">Shop Collection <span aria-hidden="true">↗</span></Link><Link className="text-link" href="/new-arrivals">Explore New Arrivals</Link></div><p className="hero-footnote">A connection to nature. A reflection of you.</p></div><div className="hero-art"><Image src="/images/beaded-necklaces.svg" alt="Illustrative green beaded necklace on a warm neutral background" fill priority sizes="(max-width: 959px) 100vw, 55vw"/><div className="art-caption"><span>THE EVERYDAY COLLECTION</span><span>01 / BEADED NECKLACES</span></div></div></div></section>
<section className="section container" id="collections"><div className="section-heading"><div><p className="eyebrow">FIND YOUR NATURAL FIT</p><h2>Little things. Lasting favorites.</h2></div><Link className="text-link" href="/collections">Explore collections <span aria-hidden="true">↗</span></Link></div><div className="collection-grid">{collections.map((c,i)=><Link className="collection-card" key={c.slug} href={`/collections/${c.slug}`}><div className="collection-image"><Image src={c.image} alt={`${c.name} illustration placeholder`} fill sizes="(max-width: 599px) 45vw, (max-width: 959px) 30vw, 18vw"/></div><div><h3>{c.name}</h3><span aria-hidden="true">↗</span></div><p className="small">0{i+1} / THE COLLECTION</p></Link>)}</div></section>
<section className="section featured"><div className="container"><div className="section-heading"><div><p className="eyebrow">THE EVERYDAY EDIT</p><h2>Meet your new favorites.</h2></div><Link className="text-link" href="/shop">View all pieces <span aria-hidden="true">↗</span></Link></div><p className="preview-note">A first look at our collection — illustrative images and sample prices.</p><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
<section className="section container story"><div className="story-art"><Image src="/images/bracelets.svg" alt="Green beaded bracelet illustration placeholder" fill sizes="(max-width: 959px) 90vw, 45vw"/><span className="story-art-label">INSPIRED BY THE NATURAL WORLD</span></div><div className="story-copy"><p className="eyebrow">OUR STORY</p><h2>Made for the moments<br/>that make a life.</h2><p>The pieces we reach for every day become part of our story. We’re building a jewelry collection around natural character, thoughtful design and lasting everyday appeal.</p><Link className="text-link" href="/about">Get to know us <span aria-hidden="true">↗</span></Link></div></section>
<section className="jade-section"><div className="container"><div className="jade-heading"><p className="eyebrow">NATURE SETS THE TONE</p><h2>Beauty in the details.<br/><em>Character in every piece.</em></h2><Link className="text-link" href="/our-jade">Explore Our Jade <span aria-hidden="true">↗</span></Link></div><div className="values-grid"><article><span>01</span><h3>Natural character</h3><p>Color and texture can vary in natural materials. Those differences are part of their appeal.</p></article><article><span>02</span><h3>A considered selection</h3><p>Our collection takes shape around color, proportion and a comfortable everyday feel.</p></article><article><span>03</span><h3>More of the story</h3><p>We’ll share verified material details and a closer look at the journey from stone to finished piece.</p></article></div></div></section>
</main>;
}
